daily_work_homepage:
    path:     /
    defaults: { _controller: DailyWorkBundle:Default:index }

daily_work_homepage2:
    path:     /xss/
    defaults: { _controller: DailyWorkBundle:Default:index2 }    
    
actualizar_probsaude:
    path: /dw/update/
    
actualizar_ps:
    path: /dw/update/{id_pac_prob}
    defaults: { _controller: DailyWorkBundle:MedicalConsultation:updateProbSaude }
    
new_probsaude_url:
    path: /dw/new/
new_probsaude:
    path: /dw/new/{idPaciente}
    defaults: { _controller: DailyWorkBundle:MedicalConsultation:newProbSaude }
    
delete_probsaude:
    path: /dw/delete/
    defaults: { _controller: DailyWorkBundle:MedicalConsultation:deleteProbSaude }

daily_work:
    path:    /dw/
    defaults: { _controller: DailyWorkBundle:Default:daily_work }

consulta_page:
    path: /dw/{id_paciente}
    defaults: { _controller: DailyWorkBundle:MedicalConsultation:consulta }

actualizar_page:
    path: /dw/dw_e/{id_paciente}
    defaults: { _controller: DailyWorkBundle:Default:actualizar }

actualizar_paciente_url:    
    path: /pac/

actualizar_paciente:
    path: /pac/{id_paciente}
    defaults: { _controller: DailyWorkBundle:MedicalConsultation:updateDadosPaciente }
    
actualizar_responsavel_url:
    path: /resp/
    
actualizar_responsavel:
    path: /resp/{id_paciente}
    defaults: { _controller: DailyWorkBundle:MedicalConsultation:updateResponsavels }

cancel_responsavel_url:
    path: /resp/cancel/
    
cancel_responsavel: 
    path: /resp/cancel/{id_paciente}
    defaults: { _controller: DailyWorkBundle:MedicalConsultation:cancelResposavels }
        
view_consulta_url: 
    path: /cons/

view_consulta: 
    path: /cons/{id_paciente}/{page}
    defaults: { _controller: DailyWorkBundle:MedicalConsultation:consultasView }

one_consulta_url:
    path: /con/
   
one_consulta:
    path: /con/{id_consulta}
    defaults: { _controller: DailyWorkBundle:MedicalConsultation:oneConsulta }

atendimento:
    path:    /at/{id_paciente}
    defaults: { _controller: DailyWorkBundle:Default:atendimento, id_paciente:default_id_paciente }
    
atendimento_seg:
    path:    /atseg/
    defaults: { _controller: DailyWorkBundle:Default:atendimentoSeg}    

to_reports:
    path:    /torep/
    defaults: { _controller: DailyWorkBundle:Default:toRep}    

