<?php

namespace Proxies\__CG__\EntityBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Paciente extends \EntityBundle\Entity\Paciente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'idPaciente', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'edad', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'nome', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'dataNascimento', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'problemasGravidez', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'leiteArtificial', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'sex', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'active', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'depressaoPuerperal', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'problemasPosparto', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'leiteMaternoExclusivo', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'leiteMaternoIdade', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'tipoParto', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'tipoSanguineo', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'pacienteCuidados', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'pacienteproblemasSaude', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'ordenResponsavels', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'consulta');
        }

        return array('__isInitialized__', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'idPaciente', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'edad', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'nome', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'dataNascimento', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'problemasGravidez', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'leiteArtificial', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'sex', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'active', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'depressaoPuerperal', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'problemasPosparto', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'leiteMaternoExclusivo', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'leiteMaternoIdade', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'tipoParto', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'tipoSanguineo', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'pacienteCuidados', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'pacienteproblemasSaude', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'ordenResponsavels', '' . "\0" . 'EntityBundle\\Entity\\Paciente' . "\0" . 'consulta');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Paciente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getEdad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdad', array());

        return parent::getEdad();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdad($edad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdad', array($edad));

        return parent::setEdad($edad);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPaciente()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdPaciente();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPaciente', array());

        return parent::getIdPaciente();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataNascimento($dataNascimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataNascimento', array($dataNascimento));

        return parent::setDataNascimento($dataNascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataNascimento', array());

        return parent::getDataNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setProblemasGravidez($problemasGravidez)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProblemasGravidez', array($problemasGravidez));

        return parent::setProblemasGravidez($problemasGravidez);
    }

    /**
     * {@inheritDoc}
     */
    public function getProblemasGravidez()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProblemasGravidez', array());

        return parent::getProblemasGravidez();
    }

    /**
     * {@inheritDoc}
     */
    public function setSex($sex)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSex', array($sex));

        return parent::setSex($sex);
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', array($active));

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function setLeiteArtificial($leiteArtificial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeiteArtificial', array($leiteArtificial));

        return parent::setLeiteArtificial($leiteArtificial);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeiteArtificial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeiteArtificial', array());

        return parent::getLeiteArtificial();
    }

    /**
     * {@inheritDoc}
     */
    public function getSex()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSex', array());

        return parent::getSex();
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', array());

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepressaoPuerperal($depressaoPuerperal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepressaoPuerperal', array($depressaoPuerperal));

        return parent::setDepressaoPuerperal($depressaoPuerperal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepressaoPuerperal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepressaoPuerperal', array());

        return parent::getDepressaoPuerperal();
    }

    /**
     * {@inheritDoc}
     */
    public function setProblemasPosparto($problemasPosparto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProblemasPosparto', array($problemasPosparto));

        return parent::setProblemasPosparto($problemasPosparto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProblemasPosparto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProblemasPosparto', array());

        return parent::getProblemasPosparto();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeiteMaternoExclusivo($leiteMaternoExclusivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeiteMaternoExclusivo', array($leiteMaternoExclusivo));

        return parent::setLeiteMaternoExclusivo($leiteMaternoExclusivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeiteMaternoExclusivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeiteMaternoExclusivo', array());

        return parent::getLeiteMaternoExclusivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeiteMaternoIdade($leiteMaternoIdade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeiteMaternoIdade', array($leiteMaternoIdade));

        return parent::setLeiteMaternoIdade($leiteMaternoIdade);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeiteMaternoIdade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeiteMaternoIdade', array());

        return parent::getLeiteMaternoIdade();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoParto(\EntityBundle\Entity\TipoParto $tipoParto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoParto', array($tipoParto));

        return parent::setTipoParto($tipoParto);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoParto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoParto', array());

        return parent::getTipoParto();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoSanguineo(\EntityBundle\Entity\TipoSanguineo $nTipoSanguineo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoSanguineo', array($nTipoSanguineo));

        return parent::setTipoSanguineo($nTipoSanguineo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoSanguineo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoSanguineo', array());

        return parent::getTipoSanguineo();
    }

    /**
     * {@inheritDoc}
     */
    public function getPacienteCuidados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPacienteCuidados', array());

        return parent::getPacienteCuidados();
    }

    /**
     * {@inheritDoc}
     */
    public function addPacienteCuidado(\EntityBundle\Entity\Paciente_Cuidado $nCuidados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPacienteCuidado', array($nCuidados));

        return parent::addPacienteCuidado($nCuidados);
    }

    /**
     * {@inheritDoc}
     */
    public function removePacienteCuidado(\EntityBundle\Entity\Paciente_Cuidado $nCuidados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePacienteCuidado', array($nCuidados));

        return parent::removePacienteCuidado($nCuidados);
    }

    /**
     * {@inheritDoc}
     */
    public function getCuidados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuidados', array());

        return parent::getCuidados();
    }

    /**
     * {@inheritDoc}
     */
    public function addPacienteProblemasSaude(\EntityBundle\Entity\Paciente_ProblemasSaude $p_problemassaude = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPacienteProblemasSaude', array($p_problemassaude));

        return parent::addPacienteProblemasSaude($p_problemassaude);
    }

    /**
     * {@inheritDoc}
     */
    public function getPacienteProblemasSaude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPacienteProblemasSaude', array());

        return parent::getPacienteProblemasSaude();
    }

    /**
     * {@inheritDoc}
     */
    public function removePacienteProblemasSaude(\EntityBundle\Entity\Paciente_ProblemasSaude $p_problemassaude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePacienteProblemasSaude', array($p_problemassaude));

        return parent::removePacienteProblemasSaude($p_problemassaude);
    }

    /**
     * {@inheritDoc}
     */
    public function getProblemasSaude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProblemasSaude', array());

        return parent::getProblemasSaude();
    }

    /**
     * {@inheritDoc}
     */
    public function getOresponsavel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOresponsavel', array());

        return parent::getOresponsavel();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrdenResponsavel(\EntityBundle\Entity\Orden_Responsavel $o_responsavel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrdenResponsavel', array($o_responsavel));

        return parent::addOrdenResponsavel($o_responsavel);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrdenResponsavel(\EntityBundle\Entity\Orden_Responsavel $o_responsavel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrdenResponsavel', array($o_responsavel));

        return parent::removeOrdenResponsavel($o_responsavel);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdenResponsavels()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdenResponsavels', array());

        return parent::getOrdenResponsavels();
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsavels()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsavels', array());

        return parent::getResponsavels();
    }

    /**
     * {@inheritDoc}
     */
    public function addConsulta(\EntityBundle\Entity\Consulta $consulta = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addConsulta', array($consulta));

        return parent::addConsulta($consulta);
    }

    /**
     * {@inheritDoc}
     */
    public function removeConsulta(\EntityBundle\Entity\Consulta $consulta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeConsulta', array($consulta));

        return parent::removeConsulta($consulta);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsulta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsulta', array());

        return parent::getConsulta();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
