reports_homepage:
    path:  /
    defaults: { _controller: ReportsBundle:Default:index }

reports_delete:
    path: /d/
    defaults: {_controller: ReportsBundle:Default:deleteJS }
    
reports_export:
    path: /e/
    defaults: {_controller: ReportsBundle:Default:exp }

    

 
    