<?php

namespace Proxies\__CG__\EntityBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Consulta extends \EntityBundle\Entity\Consulta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EntityBundle\\Entity\\Consulta' . "\0" . 'idConsulta', '' . "\0" . 'EntityBundle\\Entity\\Consulta' . "\0" . 'data', '' . "\0" . 'EntityBundle\\Entity\\Consulta' . "\0" . 'observacao', '' . "\0" . 'EntityBundle\\Entity\\Consulta' . "\0" . 'paciente', '' . "\0" . 'EntityBundle\\Entity\\Consulta' . "\0" . 'receita', '' . "\0" . 'EntityBundle\\Entity\\Consulta' . "\0" . 'metodo');
        }

        return array('__isInitialized__', '' . "\0" . 'EntityBundle\\Entity\\Consulta' . "\0" . 'idConsulta', '' . "\0" . 'EntityBundle\\Entity\\Consulta' . "\0" . 'data', '' . "\0" . 'EntityBundle\\Entity\\Consulta' . "\0" . 'observacao', '' . "\0" . 'EntityBundle\\Entity\\Consulta' . "\0" . 'paciente', '' . "\0" . 'EntityBundle\\Entity\\Consulta' . "\0" . 'receita', '' . "\0" . 'EntityBundle\\Entity\\Consulta' . "\0" . 'metodo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Consulta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdConsulta()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdConsulta();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdConsulta', array());

        return parent::getIdConsulta();
    }

    /**
     * {@inheritDoc}
     */
    public function getReceita()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReceita', array());

        return parent::getReceita();
    }

    /**
     * {@inheritDoc}
     */
    public function setReceita($receita)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReceita', array($receita));

        return parent::setReceita($receita);
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', array($data));

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', array());

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacao($observacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacao', array($observacao));

        return parent::setObservacao($observacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacao', array());

        return parent::getObservacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaciente(\EntityBundle\Entity\Paciente $paciente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaciente', array($paciente));

        return parent::setPaciente($paciente);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaciente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaciente', array());

        return parent::getPaciente();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetodo($metodo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetodo', array($metodo));

        return parent::setMetodo($metodo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetodo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetodo', array());

        return parent::getMetodo();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
