<?php

namespace Proxies\__CG__\EntityBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cuidados extends \EntityBundle\Entity\Cuidados implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EntityBundle\\Entity\\Cuidados' . "\0" . 'idCuidado', '' . "\0" . 'EntityBundle\\Entity\\Cuidados' . "\0" . 'nomeCuidado', '' . "\0" . 'EntityBundle\\Entity\\Cuidados' . "\0" . 'pacienteCuidado');
        }

        return array('__isInitialized__', '' . "\0" . 'EntityBundle\\Entity\\Cuidados' . "\0" . 'idCuidado', '' . "\0" . 'EntityBundle\\Entity\\Cuidados' . "\0" . 'nomeCuidado', '' . "\0" . 'EntityBundle\\Entity\\Cuidados' . "\0" . 'pacienteCuidado');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cuidados $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCuidado()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCuidado();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCuidado', array());

        return parent::getIdCuidado();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeCuidado($nomeCuidado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeCuidado', array($nomeCuidado));

        return parent::setNomeCuidado($nomeCuidado);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeCuidado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeCuidado', array());

        return parent::getNomeCuidado();
    }

    /**
     * {@inheritDoc}
     */
    public function getPacienteCuidado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPacienteCuidado', array());

        return parent::getPacienteCuidado();
    }

    /**
     * {@inheritDoc}
     */
    public function addPacienteCuidado(\EntityBundle\Entity\Paciente_Cuidado $p_cuidado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPacienteCuidado', array($p_cuidado));

        return parent::addPacienteCuidado($p_cuidado);
    }

    /**
     * {@inheritDoc}
     */
    public function removePacienteCuidado(\EntityBundle\Entity\Paciente_Cuidado $p_cuidado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePacienteCuidado', array($p_cuidado));

        return parent::removePacienteCuidado($p_cuidado);
    }

    /**
     * {@inheritDoc}
     */
    public function getPacientes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPacientes', array());

        return parent::getPacientes();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
